const appname = "Minsiida";
const appversion = "Version 1.0.0";
const credits = "@Minsiida Team";
const email = "E-mail";
const emailHint = "admin@admin.com";
const password = "Mot de passe";
const passwordHint = "******";
const retypePassword = "Retaper le mot de passe";
const name = "Nom et Prénom";
const userName = "Nom d'utilisateur";
const nameHint = "Minsiida Devs";
const userNameHint = "Minsiida7852";
const forgetPass = "Mot de passe oublié";
const login = "Se connecter";
const signup = "S'inscrire";
const logout = "Se déconnecter";
const createNewAccount = "ou, créer un nouveau compte";
const loginWith = "Se connecter avec";
const loggedin = "Connexion réussie";
const loggedout = "Déconnexion réussie";
const privacyPolicy = "Politique de confidentialité";
const termAndCond = "Conditions générales";
const alreadyHaveAccount = "Vous avez déjà un compte?";
const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
const menu = "Menu";
const favorites = "Favorites";
const search = "Search";
const authToken = "auth_token";
const user = "user";

const error = "Erreur";
//const baseUrl = "http://10.0.2.2:8080";
const baseUrl = "http://app.minsiida.com:8080/";
